### ISSUE TITLE
catkin build about fcl error 

### ISSUE THREAD

**Issue by Wayne-xixi** [flexible-collision-library/fcl#431]
Hello, I got this error when I catkin build path_planning from https://github.com/ayushgaud/path_planning. I use FCL 0.5.0 on ubuntu 16.04 and ros-kinetic. I dont know if this error is because of fcl version. Because someone else can successfully catkin build with FCL 0.5.0. Anyone can help me , thanks!

```_CMakeFiles/path_planning_node.dir/src/path_planning.cpp.o: In function `fcl::Transform3f::transform(fcl::Vec3fX<fcl::details::Vec3Data<double> > const&) const':
path_planning.cpp:(.text._ZNK3fcl11Transform3f9transformERKNS_6Vec3fXINS_7details8Vec3DataIdEEEE[_ZNK3fcl11Transform3f9transformERKNS_6Vec3fXINS_7details8Vec3DataIdEEEE]+0x46): undefined reference to `fcl::Quaternion3f::transform(fcl::Vec3fX<fcl::details::Vec3Data<double> > const&) const'
CMakeFiles/path_planning_node.dir/src/path_planning.cpp.o: In function `fcl::CollisionGeometry::CollisionGeometry()':
path_planning.cpp:(.text._ZN3fcl17CollisionGeometryC2Ev[_ZN3fcl17CollisionGeometryC5Ev]+0x34): undefined reference to `fcl::AABB::AABB()'
CMakeFiles/path_planning_node.dir/src/path_planning.cpp.o: In function `fcl::CollisionObject::CollisionObject(std::shared_ptr<fcl::CollisionGeometry> const&)':
path_planning.cpp:(.text._ZN3fcl15CollisionObjectC2ERKSt10shared_ptrINS_17CollisionGeometryEE[_ZN3fcl15CollisionObjectC5ERKSt10shared_ptrINS_17CollisionGeometryEE]+0x59): undefined reference to `fcl::AABB::AABB()'
CMakeFiles/path_planning_node.dir/src/path_planning.cpp.o: In function `fcl::Box::Box(double, double, double)':
path_planning.cpp:(.text._ZN3fcl3BoxC2Eddd[_ZN3fcl3BoxC5Eddd]+0x29): undefined reference to `vtable for fcl::Box'
CMakeFiles/path_planning_node.dir/src/path_planning.cpp.o: In function `planner::isStateValid(ompl::base::State const*)':
path_planning.cpp:(.text._ZN7planner12isStateValidEPKN4ompl4base5StateE[_ZN7planner12isStateValidEPKN4ompl4base5StateE]+0x1e5): undefined reference to `fcl::collide(fcl::CollisionObject const*, fcl::CollisionObject const*, fcl::CollisionRequest const&, fcl::CollisionResult&)'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/fapsros/catkin_ws/devel/.private/path_planning/lib/path_planning/path_planning_node] Error 1
make[1]: *** [CMakeFiles/path_planning_node.dir/all] Error 2
make: *** [all] Error 2_```

**Comment by Wayne-xixi** [comment]
And this is my include head. 
```
#include "fcl/config.h"
#include "fcl/octree.h"
#include "fcl/traversal/traversal_node_octree.h"
#include "fcl/collision.h"
#include "fcl/broadphase/broadphase.h"
#include "fcl/math/transform.h" ```

**Comment by jlack1987** [comment]
that appears to be some library linking issue, likely something that would be fixed in your `CMakeLists.txt`

**Comment by Wayne-xixi** [comment]
fixed thanks

**Comment by LuckyBarbara** [comment]
hello  doyou solve the problem? I have similar one with you
